// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook;

  gradebook = angular.module('gradebook-app', []);

  gradebook.controller('ClassSelect', function($scope, $http, $rootScope) {
    $scope.classes = [];
    $http.get('/api/classes/taughtByMe/').success(function(result) {
      return angular.forEach(result, function(item) {
        return $scope.classes.push(item);
      });
    });
    return $scope.loadGradeBook = function(id) {
      return $rootScope.gradebook_id = id;
    };
  });

  gradebook.controller('gradebook-view', function($scope, $rootScope, $http) {
    var class_id, refreshGradingScale;
    class_id = $rootScope.$watch('gradebook_id', function() {
      if (!$rootScope.gradebook_id) {
        return;
      }
      $http.get('/api/classes/' + $rootScope.gradebook_id + '/gradebook/').success(function(result) {
        $scope.breadcrumb = result.breadcrumb;
        $scope.events = result.events;
        $scope.gradebook = result.gradebook;
        return $scope.students = result.students;
      });
      return class_id = $rootScope.gradebook_id;
    });
    refreshGradingScale = true;
    return $scope.toggleGradingScale = function() {
      if (refreshGradingScale) {
        $http.get('/api/classes/' + class_id + '/gradingScale/').success(function(result) {
          return $scope.gradingScale = result;
        });
        refreshGradingScale = false;
      }
      return $scope.showGradingScale = !$scope.showGradingScale;
    };
  });

  gradebook.directive('gsc', function() {
    return {
      restrict: 'AE',
      templateUrl: '../templates/gradebook/gradingScale.html',
      controller: [
        '$scope', function($scope) {
          $scope.updateLowers = function() {
            console.log("Updating lowers");
            console.log($scope.gradingScale);
            return angular.forEach($scope.gradingScale.categories, function(category) {
              return console.log(category);
            });
          };
          return $scope.updateUppers = function() {
            return console.log("Updating uppers");
          };
        }
      ]
    };
  });

}).call(this);
