// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook, updateCategoryLowers, updateCategoryUppers;

  gradebook = angular.module('gradebook-app', []);

  gradebook.controller('ClassSelect', function($scope, $http, $rootScope) {
    $scope.classes = [];
    $http.get('/api/classes/taughtByMe/').success(function(result) {
      return angular.forEach(result, function(item) {
        return $scope.classes.push(item);
      });
    });
    return $scope.loadGradeBook = function(id) {
      return $rootScope.gradebook_id = id;
    };
  });

  gradebook.controller('gradebook-view', function($scope, $rootScope, $http) {
    var class_id, refreshGradingScale;
    class_id = $rootScope.$watch('gradebook_id', function() {
      if (!$rootScope.gradebook_id) {
        return;
      }
      $http.get('/api/classes/' + $rootScope.gradebook_id + '/gradebook/').success(function(result) {
        $scope.breadcrumb = result.breadcrumb;
        $scope.events = result.events;
        $scope.gradebook = result.gradebook;
        return $scope.students = result.students;
      });
      return class_id = $rootScope.gradebook_id;
    });
    refreshGradingScale = true;
    return $scope.toggleGradingScale = function() {
      if (refreshGradingScale) {
        $http.get('/api/classes/' + class_id + '/gradingScale/').success(function(result) {
          $scope.gradingScale = result;
          return updateCategoryUppers();
        });
        refreshGradingScale = false;
      }
      return $scope.showGradingScale = !$scope.showGradingScale;
    };
  });

  gradebook.directive('gsc', function() {
    return {
      restrict: 'AE',
      templateUrl: '../templates/gradebook/gradingScale.html',
      link: function(scope, elem, attrs) {
        scope.updateLower = function() {
          return console.log('updating lowers');
        };
        return scope.updateUppers = function() {
          return console.log('updating uppers');
        };
      }
    };
  });

  updateCategoryUppers = function() {
    return $('.category').not(':first').each(function() {
      return $(this).find('.categoryUpper').val(parseFloat($(this).parent().children().eq($(this).index() - 1).find('.categoryLower').val()));
    });
  };

  updateCategoryLowers = function() {
    return $('.category').not(':last').each(function() {
      return $(this).find('.categoryLower').val(parseFloat($(this).parent().children().eq($(this).index() + 1).find('.categoryUpper').val()));
    });
  };

}).call(this);
