// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook;

  gradebook = angular.module('gradebook-app', []);

  gradebook.controller('ClassSelect', function($scope, $http, $rootScope) {
    $scope.classes = [];
    $http.get('/api/classes/taughtByMe/').success(function(result) {
      return angular.forEach(result, function(item) {
        return $scope.classes.push(item);
      });
    });
    return $scope.loadGradeBook = function(id) {
      return $rootScope.gradebook_id = id;
    };
  });

  gradebook.controller('gradebook-view', function($scope, $rootScope, $http) {
    var class_id, refreshGradingScale;
    class_id = $rootScope.$watch('gradebook_id', function() {
      if (!$rootScope.gradebook_id) {
        return;
      }
      $http.get('/api/classes/' + $rootScope.gradebook_id + '/gradebook/').success(function(result) {
        $scope.breadcrumb = result.breadcrumb;
        $scope.events = result.events;
        $scope.gradebook = result.gradebook;
        return $scope.students = result.students;
      });
      return class_id = $rootScope.gradebook_id;
    });
    refreshGradingScale = true;
    return $scope.toggleGradingScale = function() {
      if (refreshGradingScale) {
        $http.get('/api/classes/' + class_id + '/gradingScale/').success(function(result) {
          console.log(result);
          $scope.gradingScale = result;
          return $scope.updateUppers();
        });
        refreshGradingScale = false;
      }
      return $scope.showGradingScale = !$scope.showGradingScale;
    };
  });

  gradebook.directive('gsc', function() {
    return {
      restrict: 'AE',
      templateUrl: '../templates/gradebook/gradingScale.html',
      link: function(scope, elem, attrs) {
        scope.updateUppers = function() {
          return angular.forEach(scope.gradingScale.categories, function(category, key) {
            var cont, prev;
            cont = true;
            if (key === 0) {
              category.upper = 100;
              cont = false;
            }
            if (cont) {
              prev = scope.gradingScale.categories[key - 1];
              return category.upper = prev.lower;
            }
          });
        };
        scope.updateLowers = function() {
          return angular.forEach(scope.gradingScale.categories, function(category, key) {
            var cont, next;
            cont = true;
            if (key === scope.gradingScale.categories.length - 1) {
              category.lower = 0;
              cont = false;
            }
            if (cont) {
              next = scope.gradingScale.categories[key + 1];
              return category.lower = next.upper;
            }
          });
        };
        return $scope.applyScale = function() {};
      }
    };
  });

}).call(this);
