// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook, _;

  _ = window._;

  gradebook = angular.module('gradebook-app', ['ngCookies', 'gradebook', 'gsc', 'wc', 'utilities']);

  gradebook.run([
    '$http', '$cookies', function($http, $cookies) {
      $http.defaults.headers.post['X-CSRFToken'] = $cookies.csrftoken;
      return $http.defaults.headers.common['X-CSRFToken'] = $cookies.csrftoken;
    }
  ]);

  gradebook.controller('ClassSelect', function($scope, $http, $rootScope) {
    $scope.classes = [];
    $http.get('/api/classes/taughtByMe/').success(function(result) {
      return angular.forEach(result, function(item) {
        return $scope.classes.push(item);
      });
    });
    return $scope.loadGradeBook = function(id) {
      $rootScope.gradebook_id = id;
      return $rootScope.$broadcast('load gradebook');
    };
  });

  gradebook.controller('gradebook-view', function($scope, $rootScope, $http) {
    var class_id, refreshGradingScale, refreshWeights;
    class_id = refreshWeights = true;
    refreshGradingScale = true;
    $rootScope.$on('load gradebook', function() {
      if (!$rootScope.gradebook_id) {
        return;
      }
      $http.get('/api/classes/' + $rootScope.gradebook_id + '/gradebook/').success(function(result) {
        $scope.breadcrumb = result.breadcrumb;
        $scope.events = result.events;
        $scope.gradebook = result.gradebook;
        $scope.students = result.students;
        class_id = $rootScope.gradebook_id;
        $rootScope.$broadcast('recalculateAverages');
        return $scope.hideGradebook = false;
      });
      refreshWeights = true;
      refreshGradingScale = true;
      $scope.displayWeightControl = false;
      return $scope.showGradingScale = false;
    });
    $scope.toggleWeightControl = function() {
      if (refreshWeights) {
        $scope.loadWeights();
        refreshWeights = false;
      }
      return $scope.displayWeightControl = !$scope.displayWeightControl;
    };
    return $scope.toggleGradingScale = function() {
      if (refreshGradingScale) {
        $scope.loadGradingScale();
        refreshGradingScale = false;
      }
      return $scope.showGradingScale = !$scope.showGradingScale;
    };
  });

}).call(this);
