// Generated by CoffeeScript 1.7.1
(function() {
  var components;

  components = angular.module('components', []);

  components.directive('gsc', function() {
    return {
      restrict: "A",
      replace: 'true',
      templateUrl: "'../templates/gradebook/gradingScale.html'"
    };
  });

}).call(this);
