// Generated by CoffeeScript 1.7.1
(function() {
  var _;

  _ = window._;

  angular.module('gsc', []).directive('gsc', function() {
    return {
      restrict: 'AE',
      templateUrl: '../templates/gradebook/gradingScale.html',
      controller: 'gscCtrl'
    };
  }).controller('gscCtrl', [
    '$scope', '$http', '$rootScope', function($scope, $http, $rootScope) {
      $scope.loadGradingScale = function() {
        return $http.get('/api/classes/' + $rootScope.gradebook_id + '/gradingScale/').success(function(result) {
          $scope.gradingScale = result;
          return $scope.updateUppers();
        });
      };
      $scope.updateUppers = function() {
        return angular.forEach($scope.gradingScale.categories, function(category, key) {
          var cont, prev;
          cont = true;
          if (key === 0) {
            category.upper = 100;
            cont = false;
          }
          if (cont) {
            prev = $scope.gradingScale.categories[key - 1];
            return category.upper = prev.lower;
          }
        });
      };
      $scope.updateLowers = function() {
        return angular.forEach($scope.gradingScale.categories, function(category, key) {
          var cont, next;
          cont = true;
          if (key === $scope.gradingScale.categories.length - 1) {
            category.lower = 0;
            cont = false;
          }
          if (cont) {
            next = $scope.gradingScale.categories[key + 1];
            return category.lower = next.upper;
          }
        });
      };
      $scope.deleteGradingScaleCategory = function(lower) {
        var cat;
        cat = _.findWhere($scope.gradingScale.categories, {
          lower: lower
        });
        $scope.gradingScale.categories.splice(_.indexOf($scope.gradingScale.categories, cat), 1);
        return $scope.updateUppers();
      };
      $scope.addGradingScaleCategory = function(upper) {
        var additional, cat, index, next;
        cat = _.findWhere($scope.gradingScale.categories, {
          upper: upper
        });
        index = _.indexOf($scope.gradingScale.categories, cat);
        next = $scope.gradingScale.categories[index - 1];
        additional = {
          upper: (next.upper + cat.upper) / 2,
          value: cat.value
        };
        $scope.gradingScale.categories.splice(index, 0, additional);
        return $scope.updateLowers();
      };
      return $scope.applyGradingScale = function() {
        return $http.post('/gradebook/gradingScale/setScale/', {
          gradingScale: $scope.gradingScale,
          classId: $rootScope.gradebook_id
        }).success(function(result) {
          $rootScope.$broadcast('recalculateGrades');
          return $scope.toggleGradingScale();
        });
      };
    }
  ]);

}).call(this);
