// Generated by CoffeeScript 1.7.1
(function() {
  var _;

  _ = window._;

  angular.module('utilities', []).directive('utilities', function() {
    return {
      restrict: 'AE',
      templateUrl: '../templates/gradebook/utilities.html',
      link: function(scope, element, attrs) {
        return scope.histogram = function() {
          scope.hideGradebook = true;
          return console.log('opening up histogram');
        };
      }
    };
  });

}).call(this);
