// Generated by CoffeeScript 1.7.1
(function() {
  var _;

  _ = window._;

  angular.module('utilities', []).directive('utilities', function() {
    return {
      restrict: 'AE',
      templateUrl: '../templates/gradebook/utilities.html',
      controller: 'utilitiesCtrl'
    };
  }).controller('utilitiesCtrl', ['$scope', '$http', '$rootScope', function($scope, $http, $rootScope) {}]);

}).call(this);
