// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook;

  gradebook = angular.module('gradebook', []);

  gradebook.controller('ClassSelect', function($scope) {
    return $scope.message = "hello";
  });

}).call(this);
