// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook;

  gradebook = angular.module('gradebook', []);

  gradebook.controller('ClassSelect', function($scope) {
    var data;
    $scope.message = "hello";
    return data = $http.get("/academia/api/classes");
  });

}).call(this);
