// Generated by CoffeeScript 1.7.1
(function() {
  var gradebook;

  gradebook = angular.module('gradebook-app', []);

  gradebook.controller('ClassSelect', function($scope, $http, $rootScope) {
    $scope.classes = [];
    $http.get('/api/classes/taughtByMe/').success(function(result) {
      return angular.forEach(result, function(item) {
        return $scope.classes.push(item);
      });
    });
    return $scope.loadGradeBook = function(id) {
      return $rootScope.gradebook_id = id;
    };
  });

  gradebook.controller('gradebook-view', function($scope, $rootScope, $http) {
    return $rootScope.$watch('gradebook_id', function() {
      if (!$rootScope.gradebook_id) {
        return;
      }
      $http.get('/api/events/homeworkByClass/' + $rootScope.gradebook_id).success(function(result) {
        $scope.events = [];
        return angular.forEach(result, function(item) {
          return $scope.events.push(item);
        });
      });
      return $http.get('/api/users/studentsbyClass/' + $rootScope.gradebook_id).success(function(result) {
        $scope.students = [];
        return angular.forEach(result(function(item) {
          return $scope.students.push(item);
        }));
      });
    });
  });

}).call(this);
